version: "3.9"
services:
  nginx:
    image: nginx:alpine
    container_name: waste-nginx
    ports: ["80:80"]
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./api/storage/app/public:/var/www/html/storage/app/public
      - ./frontend/dist:/var/www/frontend
    depends_on:
      - api

  api:
    build: ./api
    container_name: waste-api
    volumes:
      - ./api:/var/www/html
    working_dir: /var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_URL: http://localhost
      ML_SERVICE_URL: http://ml:9000

  ml:
    build: ./ml
    container_name: waste-ml

  frontend:
    image: node:20-alpine
    container_name: waste-frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run build"

  db:
    image: mariadb:10.6
    container_name: waste-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_waste
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      timeout: 5s
      retries: 10
